services:
  lurker:
    build: .
    container_name: lurker
    network_mode: bridge
    volumes:
      - ./data:/data
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - LURKER_PORT=9795
