services:
  lurker:
    build: .
    container_name: lurker
    network_mode: bridge
    volumes:
      - ./data:/data
    ports:
      - "9795:9795"
    restart: unless-stopped
    environment:
      - LURKER_PORT=9795
